config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :index, :show]

  resource :session, only: [:new, :create, :destroy]

  resources :subs

  resources :posts, except: :index do
    resources :comments, only: :create
  end

  resources :comments, only: [:destroy, :show]

  root to: 'subs#index'
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id                :integer          not null, primary key
#  content           :string           not null
#  author_id         :integer          not null
#  post_id           :integer          not null
#  parent_comment_id :integer
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#

class Comment < ApplicationRecord
  validates :content, presence: true

  belongs_to :author,
             class_name: :User

  belongs_to :post

  belongs_to :parent_comment,
             foreign_key: :parent_comment_id,
             class_name: :Comment,
             optional: true

  has_many :child_comments,
           foreign_key: :parent_comment_id,
           class_name: :Comment,
           dependent: :destroy
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :ensure_logged_in, except: :show

  def show
    @comment = Comment.find(params[:id])
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.post_id = params[:post_id]
    @comment.author_id = current_user.id
    unless @comment.save
      flash_store(@comment)
    end
    redirect_to request.referrer
  end

  def destroy
    @comment = Comment.find(params[:id]).delete
    redirect_to request.referrer
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :parent_comment_id)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<li>
  <br>
  "<%= comment.content %>"<br>
  by <%= link_to comment.author.username, user_url(comment.author) %>
  <br>
  <%= link_to 'View comment thread', comment_url(comment) %>
  <br>
  <% if current_user == comment.author %>
  <div class="small">
    <%= button_to 'Delete Comment',
                  comment_url(comment),
                  method: :delete,
                  data: {
                    confirm: 'Are you sure?'
                    } %>
  </div>
  <br>
  <% end %>
  <ul>
    <%= render comment.child_comments %>
  </ul>
</li>

app/views/comments/show.html.erb
<h1>
  Comment: <br>
  <%= @comment.content %>
  <div class="small">
    By: <%= link_to @comment.author.username, user_url(@comment.author) %>
  </div>
</h1>

<%= render @comment.child_comments %>

<br>

<form action="<%= post_comments_url(@comment.post) %>" method="post">
  <%= auth_token %>
  <input type="hidden" name="comment[parent_comment_id]" value="<%= @comment.id %>">
  <input type="text" name="comment[content]" placeholder="Add a reply...">
  <input type="submit" value="Add Reply">
</form>

<%= link_to 'Back', post_url(@comment.post) %>