config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :index, :show]

  resource :session, only: [:new, :create, :destroy]

  resources :subs

  resources :posts, except: :index do
    resources :comments, only: :create
  end

  resources :comments, only: [:destroy, :show]

  root to: 'subs#index'
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  attr_reader :password
  validates :password, length: { minimum: 6, allow_nil: true }
  validates :username, :password_digest, :session_token, presence: true
  validates :username, :password_digest, uniqueness: true
  after_initialize :ensure_session_token

  has_many :subs,
           foreign_key: :moderator_id,
           inverse_of: :moderator,
           dependent: :destroy

  has_many :posts,
           foreign_key: :author_id,
           inverse_of: :author,
           dependent: :destroy

  def self.generate_unique_token
    new_token = SecureRandom.urlsafe_base64
    while User.find_by(session_token: new_token)
      new_token = SecureRandom.urlsafe_base64
    end
    new_token
  end

  def self.find_by_credentials(options)
    user = User.find_by(username: options[:username])
    return user if user &&
        BCrypt::Password.new(user.password_digest).is_password?(options[:password])
    nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def ensure_session_token
    self.session_token ||= User.generate_unique_token
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login!(@user)
      redirect_to '/'
    else
      flash_now_store(@user)
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @subs = @user.subs
    @posts = @user.posts
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<h1>Sign Up</h1>

<form action="<%= users_url %>" method="post">
  <%= auth_token %>
  <label>Username:<br>
    <input type="text" name="user[username]" value="<%= @user.username %>">
  </label><br>
  <label>Password:<br>
    <input type="password" name="user[password]" value="<%= @user.password %>">
  </label><br>
  <input type="submit" value="Sign Up">
</form>

app/views/users/show.html.erb
<h1>
  User: <%= @user.username %>
</h1>
Subs: <br>
<% @subs.each do |sub| %>
  <%= link_to sub.title, sub_url(sub) %><br>
<% end %>
<br>
<br>
Posts: <br>
<% @posts.each do |post| %>
  <%= link_to post.title, post_url(post) %><br>
<% end %>