config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :index, :show]

  resource :session, only: [:new, :create, :destroy]

  resources :subs

  resources :posts, except: :index do
    resources :comments, only: :create
  end

  resources :comments, only: [:destroy, :show]

  root to: 'subs#index'
end

app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :integer          not null, primary key
#  title        :string           not null
#  description  :text             not null
#  moderator_id :integer          not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Sub < ApplicationRecord
  validates :title, presence: true

  belongs_to :moderator,
             class_name: :User

  has_many :post_subs,
           dependent: :destroy

  has_many :posts,
           through: :post_subs
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :ensure_logged_in, only: [:new, :create, :edit, :update]

  def index
    @subs = Sub.all
  end

  def show
    @sub = Sub.find(params[:id])
  end

  def new
    @sub = current_user.subs.new
  end

  def create
    @sub = current_user.subs.new(sub_params)
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash_now_store(@sub)
      render :new
    end
  end

  def edit
    @sub = Sub.find(params[:id])
  end

  def update
    @sub = Sub.find(params[:id])
    if @sub.update(sub_params)
      redirect_to sub_url(@sub)
    else
      flash_now_store(@sub)
      render :edit
    end
  end

  def destroy
    Sub.find(params[:id]).delete
    redirect_to '/'
  end

  private

  def sub_params
    params.require(:sub).permit(:title, :description)
  end
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/views/subs/edit.html.erb
<h1>
  Sub: <%= @sub.title %>
</h1>

<form action="<%= sub_url(@sub) %>" method="post">
  <%= auth_token %>
  <input type="hidden" name="_method" value="PATCH">
  <label>Sub Title: <input type="text" name="sub[title]" value="<%= @sub.title %>"></label><br>
  <label>Descrition: <textarea name="sub[description]"><%= @sub.description %></textarea></label><br>
  By: <%= @sub.moderator.username %><br>
  <input type="submit" value="Update Sub">
</form>

<%= button_to 'Cancel', sub_url(@sub), method: :get %>

app/views/subs/index.html.erb
<h1>All Subs</h1>

<% @subs.each do |sub| %>
  <strong>
    Title: <%= link_to sub.title, sub_url(sub) %><br>
    By: <%= link_to sub.moderator.username, user_url(sub.moderator) %><br>
    <br>
  </strong>
<% end %>

<%= button_to 'New Sub', new_sub_url, method: :get %>
<%= button_to 'New Post', new_post_url, method: :get %>

app/views/subs/new.html.erb
<h1>New Sub</h1>

<form action="<%= subs_url %>" method="post">
  <%= auth_token %>
  <label>Sub Title: <input type="text" name="sub[title]" value="<%= @sub.title %>"></label><br>
  <label>Descrition: <input type="text" name="sub[description]" value="<%= @sub.description %>"></label><br>
  By: <%= @sub.moderator.username %><br>
  <input type="submit" value="Create New Sub">
</form>

app/views/subs/show.html.erb
<h1>
  Sub: <%= @sub.title %>
</h1>

Description: <%= @sub.description %><br>
By: <%= link_to @sub.moderator.username, user_url(@sub.moderator) %><br>
<% if current_user == @sub.moderator %>
  <%= button_to 'Edit Sub', edit_sub_url(@sub), method: :get %>
  <%= button_to 'Delete Sub',
                sub_url(@sub),
                method: :delete,
                data: {
                  confirm: 'Are you sure?'
                  } %>
<% end %>
<br>
<br>
Posts:
<br>
<% @sub.posts.each do |post| %>
  <%= link_to post.title, post_url(post) %>
  <br>
<% end %>