config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :index, :show]

  resource :session, only: [:new, :create, :destroy]

  resources :subs

  resources :posts, except: :index do
    resources :comments, only: :create
  end

  resources :comments, only: [:destroy, :show]

  root to: 'subs#index'
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  url        :string
#  content    :string
#  author_id  :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ApplicationRecord
  validates :title, :subs, presence: true
  after_initialize :set_blank_to_nil

  belongs_to :author,
             class_name: :User

  has_many :post_subs,
           dependent: :destroy

  has_many :subs,
           through: :post_subs

  has_many :comments

  def set_blank_to_nil
    self.url = nil if self.url == ""
    self.content = nil if self.content == ""
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :ensure_logged_in, only: [:new, :create, :edit, :update]

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to post_url(@post)
    else
      flash_now_store(@post)
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_url(@post)
    else
      flash_now_store(@post)
      render :edit
    end
  end

  def destroy
    Post.find(params[:id]).delete
    redirect_to '/'
  end

  private

  def post_params
    params.require(:post).permit(:title, :url, :content, sub_ids: [])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<h1>Edit Post:
  <%= @post.title %>
</h1>

<form action="<%= post_url(@post) %>" method="post">
  <%= auth_token %>
  <input type="hidden" name="_method" value="PATCH">
  By: <%= current_user.username %><br>
  <label>Title: <input type="text" name="post[title]" value="<%= @post.title %>"></label><br>
  <label>URL: <input type="text" name="post[url]" value="<%= @post.url %>" placeholder="optional"></label><br>
  <label>Content: <input type="text" name="post[content]" value="<%= @post.content %>" placeholder="optional"></label><br>
  Subs:<br>
  <input type="hidden" name="post[subs_id][]" value="">
  <% Sub.all.each do |sub| %>
    <label>
      <input type="checkbox"
             name="post[sub_ids][]"
             value="<%= sub.id %>"
             <%= "checked" if @post.sub_ids.include?(sub.id) %>>
      <%= sub.title %>
    </label><br>
  <% end %>
  <input type="submit" value="Update Post">
</form>

<%= button_to 'Cancel', post_url(@post), method: :get %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<form action="<%= posts_url %>" method="post">
  <%= auth_token %>
  By: <%= current_user.username %><br>
  <label>Title: <input type="text" name="post[title]" value="<%= @post.title %>"></label><br>
  <label>URL: <input type="text" name="post[url]" value="<%= @post.url %>" placeholder="optional"></label><br>
  <label>Content: <input type="text" name="post[content]" value="<%= @post.content %>" placeholder="optional"></label><br>
  Subs:<br>
  <input type="hidden" name="post[subs_id][]" value="">
  <% Sub.all.each do |sub| %>
    <label>
      <input type="checkbox"
             name="post[sub_ids][]"
             value="<%= sub.id %>"
             <%= "checked" if @post.sub_ids.include?(sub.id) %>>
      <%= sub.title %>
    </label><br>
  <% end %>
  <input type="submit" value="Create New Post">
</form>

app/views/posts/show.html.erb
<h1>
  Post: <%= @post.title %>
</h1>

<strong>URL:</strong> <%= @post.url && (link_to @post.url, @post.url) || "(None)" %><br>
<strong>Content:</strong> <%= @post.content || "(None)" %><br>
<strong>Author:</strong> <%= link_to @post.author.username, user_url(@post.author) %><br>
<br>
Subs: <br>
<% @post.subs.each do |sub| %>
  <%= link_to sub.title, sub_url(sub) %><br>
<% end %>
<br>
<% if current_user == @post.author %>
  <%= (button_to 'Edit Post', edit_post_url(@post), method: :get) %>
  <%= button_to 'Delete Post',
                post_url(@post),
                method: :delete,
                data: {
                  confirm: 'Are you sure?'
                  }%>
<% end %>
<br>
<br>
<strong>Comments:</strong>

<ul>
  <%= render @post.comments.where(parent_comment_id: nil) %>
</ul>

<form action="<%= post_comments_url(@post) %>" method="post">
  <%= auth_token %>
  <input type="text" name="comment[content]" placeholder="Add a comment..."><br>
  <input type="submit" value="Add Comment">
</form>